#class Usuario:
#def __init__(Nombre,Apellidos,NumeroDeIdentificacion,ImagenDeUsuario,RegistroPrevisto,RegistroReal,RegistrosDatos,Presupuesto):
Nombre= 'String'
Apellidos= 'String'
NumeroDeIdentificacion= 'Int'
ImagenDeUsuario= 'PNG'
RegistroPrevisto= 'RegistrosDatos'
RegistroReal= 'class()'
RegistosDatos= 'class()'
Presupuesto= 0.0